# Natural Language Processing

P.S. to run again the code, please use the .csv files existed in this .zip.
The data columns had to be named. so, a slight change in .txt files load data into pandas dataframes.

## Importing the libraries

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from sklearn.metrics import confusion_matrix, accuracy_score

# Importing the dataset

In [2]:
dataset = pd.read_csv('r8-train-all-terms.txt', delimiter = '\t', quoting = 3)
test_dataset = pd.read_csv('r8-test-all-terms.txt', delimiter = '\t', quoting = 3)
dataset = dataset[pd.notnull(dataset['Example'])]
test_dataset = test_dataset[pd.notnull(dataset['Example'])]

test_dataset

C:\Users\user\AppData\Local\Temp/ipykernel_10136/653030402.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_dataset = test_dataset[pd.notnull(dataset['Example'])]


Class                                            Example
0        trade  asian exporters fear damage from u s japan rif...
1        grain  china daily says vermin eat pct grain stocks a...
2         ship  australian foreign ship ban ends but nsw ports...
3          acq  sumitomo bank aims at quick recovery from merg...
4         earn  amatil proposes two for five bonus share issue...
...        ...                                                ...
2184  money-fx  balladur insists on maintenance of louvre acco...
2185     trade  philippine trade gap widens in january august ...
2186     crude  iran soviet union to swap crude refined produc...
2187       acq  n z s chase corp makes offer for entregrowth c...
2188      ship  japan india conference cuts gulf war risk char...

[2189 rows x 2 columns]

# Cleaning the texts

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
replace_by_space_re = re.compile('[/(){}\[\]\|@,;]')
bad_symbols_re = re.compile('[^0-9a-z #+_]')

In [5]:
corpus = []
for i in range(0,5485):
    example = re.sub ('[^a-zA-Z]', ' ', dataset['Example'][i])
    example = example.lower()
    example = example.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    example = [ps.stem(word) for word in example if not word in set(all_stopwords)]
    example = ' '.join(example)
    corpus.append(example)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

test_corpus= []
for i in range(0, 2189):
    example = re.sub('[^a-zA-Z]', ' ', test_dataset['Example'][i])
    example = example.lower()
    example = example.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    # all_stopwords.remove('not')
    example = [ps.stem(word) for word in example if not word in set(all_stopwords)]
    example = ' '.join(example)
    test_corpus.append(example)

# Splitting Datasets:

In [7]:
corpus = [str(item) for item in corpus]

X_train = corpus
y_train = dataset['Class']

X_test = test_corpus
y_test = test_dataset['Class']

# Naive Bayes Classifier

In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

In [9]:
nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])

nb.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [10]:
from sklearn.metrics import classification_report
y_pred = nb.predict(X_test)

In [11]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 662    0   34    0    0    0    0    0]
 [  32   69   20    0    0    0    0    0]
 [  10    0 1073    0    0    0    0    0]
 [   5    0    5    0    0    0    0    0]
 [  32    0   37    0   10    2    0    0]
 [  59    0   15    0    0   13    0    0]
 [  28    3    3    0    0    0    0    2]
 [  20    0   19    0    0    0    0   36]]


0.8510735495660119

In [12]:
# Tokenizing
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5485)